---
- name: Add key for kibana
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Installing dependencies ...
  apt:
    name: apt-transport-https
    state: present

- name: Add Kibana repository...
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version_series }}.x/apt stable main'
    state: present

- name: Update cache...
  apt:
    update_cache: true
    cache_valid_time: 86400

# Installing logstash specific version
- name: Install Kibana specific version
  apt:
    name: kibana={{ kibana_version }}
    state: present
    update_cache: true
  when: kibana_version is defined

- name: Installing Kibana
  apt:
    name: kibana
    state: present
  when: kibana_version is undefined

- name: Adding Kibana configuration file ...
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart kibana
